### ISSUE TITLE
Any plans to support non-vault firmwares / devices?

### ISSUE THREAD

**Issue by youfoundron** [LedgerHQ/ledger-updater#3]
I have a specific use case that the updater seems capable of addressing:

I would like to be able to update device firmware on my Ledger Nano S while being disconnected from the internet.

Any plans to support more devices / firmwares would be beneficial to those who are looking for even greater security and assurance of their keys' safety.

**Comment by meriadec** [comment]
As you saw, this project is targeting Blue firmware & Vault app, but under the hoods it uses the same primitives used in Ledger Live for app & firm installation. In result, it's not more or less capable to do offline update than Live.

For offline update, I don't think it's possible right now, because the data is streamed from the HSM, requiring confirmation from device for each blob. Note that the device constantly check the integrity during the process, so there is not much of use case for offline upd (in the end you will need to download a full firm after all).

Closing for now
